name: "Turbo TSC Reviewer"
description: "Monorepo-native PR Reviews for Turborepo TypeScript (TSC) checks."
author: "Vinayaka Hebbar"
branding:
  icon: "check-circle"
  color: "blue"

inputs:
  github_token:
    description: "The GITHUB_TOKEN for posting review comments."
    required: true

runs:
  using: "node20"
  main: "dist/index.js"
